### ISSUE TITLE
Calling the command with -i results in cryptic error message

### ISSUE THREAD

**Issue by adelgado** [koreno/prebase#1]
When calling prebase such as `git prebase -i master`, one is presented with the error message

```
Traceback (most recent call last):
  File "/usr/local/bin/git-prebase", line 104, in <module>
    commits.append(line.split()[1])
IndexError: list index out of range
Could not execute editor
```

While it is not correct usage to pass in a `-i` parameter, it'd be cool to have a friendlier error message.

**Comment by koreno** [comment]
Thanks!

**Comment by adelgado** [comment]
Thank you! :-)
